import Footer from "@/components/shared/footer";
import Header from "@/components/shared/header";
import { Titillium_Web } from 'next/font/google';

const titillium_Web = Titillium_Web({
  weight: ['200', '400', '600', '700'],
  subsets: ['latin'],
})

import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={titillium_Web.className}>
      <body>

        <Header />
        {children}
        <Footer />

      </body>
    </html>
  );
}
